// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.6_@types+node@22.19.21_cac@6.7.14_db0@0.3.4_ioredis@5.11.1_ma_uvnf5wzokwvqztazeovmvxelgq/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.6_@types+node@22.19.21_cac@6.7.14_db0@0.3.4_ioredis@5.11.1_ma_uvnf5wzokwvqztazeovmvxelgq/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.6_@types+node@22.19.21_cac@6.7.14_db0@0.3.4_ioredis@5.11.1_ma_uvnf5wzokwvqztazeovmvxelgq/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.6_@types+node@22.19.21_cac@6.7.14_db0@0.3.4_ioredis@5.11.1_ma_uvnf5wzokwvqztazeovmvxelgq/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.6_@types+node@22.19.21_cac@6.7.14_db0@0.3.4_ioredis@5.11.1_ma_uvnf5wzokwvqztazeovmvxelgq/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.6_@types+node@22.19.21_cac@6.7.14_db0@0.3.4_ioredis@5.11.1_ma_uvnf5wzokwvqztazeovmvxelgq/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.6_@types+node@22.19.21_cac@6.7.14_db0@0.3.4_ioredis@5.11.1_ma_uvnf5wzokwvqztazeovmvxelgq/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.6_@types+node@22.19.21_cac@6.7.14_db0@0.3.4_ioredis@5.11.1_ma_uvnf5wzokwvqztazeovmvxelgq/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@pinia+nuxt@0.5.5_magicast@0.5.3_typescript@5.9.3_vue@3.5.38_typescript@5.9.3_/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.6_@types+node@22.19.21_cac@6.7.14_db0@0.3.4_ioredis@5.11.1_ma_uvnf5wzokwvqztazeovmvxelgq/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.6_@types+node@22.19.21_cac@6.7.14_db0@0.3.4_ioredis@5.11.1_ma_uvnf5wzokwvqztazeovmvxelgq/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@1.7.0_rollup@4.62.0_vite@6.4.3_@types+node@22.19.21_jiti@2.7.0_terser@5.48.0_t_m2n5svyh7vstuo3ojzlbaqogku/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@1.7.0_rollup@4.62.0_vite@6.4.3_@types+node@22.19.21_jiti@2.7.0_terser@5.48.0_t_m2n5svyh7vstuo3ojzlbaqogku/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.6_@types+node@22.19.21_cac@6.7.14_db0@0.3.4_ioredis@5.11.1_ma_uvnf5wzokwvqztazeovmvxelgq/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.6_@types+node@22.19.21_cac@6.7.14_db0@0.3.4_ioredis@5.11.1_ma_uvnf5wzokwvqztazeovmvxelgq/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../plugins/gsap.client")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
